import "./globals.css";
import { Inter, Lato } from "next/font/google";
import { Providers } from "./providers";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <body className={lato.className}>
          <Providers>{children}</Providers>
        </body>
      </html>
    </>
  );
}
